# Generated by Django 4.0.8 on 2024-09-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_newsandevents_id_alter_semester_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('subject', models.TextField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('upload_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
