# Generated by Django 4.0.8 on 2024-09-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_uploaddocument_userinterface_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyingstudent',
            name='level',
            field=models.CharField(choices=[('Daycear', 'Daycear'), ('Primary', 'Primary'), ('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Daycear', 'Daycear'), ('Primary', 'Primary'), ('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='level',
            field=models.CharField(choices=[('Daycear', 'Daycear'), ('Primary', 'Primary'), ('Junior Secondary', 'Junior Secondary'), ('Senior Secondary', 'Senior Secondary')], max_length=25, null=True),
        ),
    ]
