# Generated by Django 4.0.8 on 2024-10-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_applyingstudent_level_alter_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='switch',
            field=models.BooleanField(default=False),
        ),
    ]
